version: "3"

networks:
  backend:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks: 
      - backend

  php-fpm:
    image: php:fpm-alpine
    networks: 
      - backend

### DataBase ###
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: -------------
    networks: 
      - backend
  
  redis:
    image: redis:4
    networks: 
      - backend
